[project]
name = "backend"
version = "0.1.0"
description = "The legend backend server of WapSudal"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "fastapi[standard]>=0.122.0",
    "psycopg[binary]>=3.2.13",
    "sqlmodel>=0.0.27",
]
